_target_: src.models.timm_module.TimmLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.timm_cifar_net.SimpleTimmNet
  input_size: 32
  model_name: resnet18
  num_classes: 10
