_target_: src.datamodules.glue_datamodule.GLUEDataModule
model_name_or_path: ${model.model_name_or_path} # but always get model.model_name_or_path
task_name: 'cola'
max_seq_length: 128
train_batch_size: 32
eval_batch_size: 32